### ISSUE TITLE
[Question] HW2 test case: loop3

### ISSUE THREAD

**Issue by leedongjin001224** [gist-pal/ec3204-pl-and-compilers#8]
Name: Dongjin Lee

Question in one sentence:
Why is the assertion "assert (10<=y)" marked as "cannot be proven using our interval analysis" even though "x==10" is verified at the same time?

Detailed situation (optional):
In HW2, within the test file loop3, the code includes the following assertions after the while loop:

assert (x==10 && 0<=y); (* safe, provable *) 
assert (10<=y); (* safe, but cannot be proven using our interval analysis *) 

I understand that the truth of "x==10" was verified by explicitly running the while loop a limited number of times, as stated in hw2.pdf, but not by finding the fixed point in the manner described in Lecture13.pdf (p.11).
However, I am struggling to understand why "assert (10<=y)" is marked as "cannot be proven using our interval analysis," even though this assertion is also true at the end of the loop.
I think the only difference is that only "x" would be filtered by the loop condition, but it seems unreasonable to apply clearer intervals only to "x" while restricting direct execution of the while loop to a finite number of times.

Is there another reason for this?
Please let me know if there’s something I am misunderstanding.

Thank you.

**Comment by sunbeomso** [comment]
Hi @leedongjin001224 ,

Thank you for asking this question. Feel free to post follow-up questions if something is still unclear.

---

> I understand that the truth of "x==10" was verified by explicitly running the while loop a limited number of times, as stated in hw2.pdf, but not by finding the fixed point in the manner described in Lecture13.pdf (p.11).
> ...
> I think the only difference is that only "x" would be filtered by the loop condition, but it seems unreasonable to apply clearer intervals only to "x" while restricting direct execution of the while loop to a finite number of times.

It seems there might be a slight misunderstanding. "x==10" can be proven by computing a fixed point!

Through a fixed computation with narrowing, we obtain x=[0,10] **at the loop entry.** By combining this condition with the loop termination condition "x>=10" (i.e., by designing a suitable "filter" function on p.18),  we obtain x = [10,10].

The interval analysis that we covered in class does not involve "direct" execution (even if it is possible to design your own analysis that works as you suggested).

---
> _However, I am struggling to understand why "assert (10<=y)" is marked as "cannot be proven using our interval analysis," even though this assertion is also true at the end of the loop._

Please recall that not all true properties (assertions) are mechanically provable. Analyzing semantic properties is generally undecidable.

**Comment by leedongjin001224** [comment]
Thank you for your guidance.

I was focusing on filtering only specific intervals to satisfy the condition, intending to use it in a narrowing operator.
Initially, I might have misinterpreted your advice regarding thresholding at a fixed point as mentioned in hw2.pdf.

Now that I’ve reviewed it more carefully, everything is clearer.
I managed to adjust my code, and it now produces the expected outputs for all the provided examples.

I truly appreciate your help.

**Comment by leedongjin001224** [comment]
> Hi @leedongjin001224 ,
> 
> Thank you for asking this question. Feel free to post follow-up questions if something is still unclear.
> 
> > I understand that the truth of "x==10" was verified by explicitly running the while loop a limited number of times, as stated in hw2.pdf, but not by finding the fixed point in the manner described in Lecture13.pdf (p.11).
> > ...
> > I think the only difference is that only "x" would be filtered by the loop condition, but it seems unreasonable to apply clearer intervals only to "x" while restricting direct execution of the while loop to a finite number of times.
> 
> It seems there might be a slight misunderstanding. "x==10" can be proven by computing a fixed point!
> 
> Through a fixed computation with narrowing, we obtain x=[0,10] **at the loop entry.** By combining this condition with the loop termination condition "x>=10" (i.e., by designing a suitable "filter" function on p.18), we obtain x = [10,10].
> 
> The interval analysis that we covered in class does not involve "direct" execution (even if it is possible to design your own "hybrid" analysis that combines concrete execution and abstract execution).
> 
> > _However, I am struggling to understand why "assert (10<=y)" is marked as "cannot be proven using our interval analysis," even though this assertion is also true at the end of the loop._
> 
> Please recall that not all true properties (assertions) are mechanically provable. Analyzing semantic properties is generally undecidable.


Thank you for your guidance.

I was focusing on filtering only specific intervals to satisfy the condition, intending to use it in a narrowing operator.
Initially, I might have misinterpreted your advice regarding thresholding at a fixed point as mentioned in hw2.pdf.

Now that I’ve reviewed it more carefully, everything is clearer.
I managed to adjust my code, and it now produces the expected outputs for all the provided examples.

I truly appreciate your help.
